[package]
name = "dev-parachain-primitives"
version = "0.1.0"
authors = ["Zenlink Developers"]
edition = "2018"

[dependencies]
# Substrate dependencies
sp-runtime = { git = 'https://github.com/paritytech/substrate', default-features = false, branch = 'polkadot-v0.9.8' }
sp-core = { git = 'https://github.com/paritytech/substrate', default-features = false, branch = 'polkadot-v0.9.8' }

[features]
default = [ "std" ]
std = [
	"sp-runtime/std",
	"sp-core/std"
]
